### ISSUE TITLE
Context creation fails on Wayland.

### ISSUE THREAD

**Issue by icefoxen** [glowcoil/raw-gl-context#4]
Sorry.  XD  Using the `sway` compositor with AMD GPU, on Debian Bullseye.

```
> env RUST_BACKTRACE=1 cargo run --example winit
    Finished dev [unoptimized + debuginfo] target(s) in 0.03s
     Running `target/debug/examples/winit`
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: InvalidWindowHandle', examples/winit.rs:10:67
stack backtrace:
   0: rust_begin_unwind
             at /rustc/25b3db3aa752d9d4633c983c9d4bf5e48f9baff1/library/std/src/panicking.rs:493:5
   1: core::panicking::panic_fmt
             at /rustc/25b3db3aa752d9d4633c983c9d4bf5e48f9baff1/library/core/src/panicking.rs:92:14
   2: core::option::expect_none_failed
             at /rustc/25b3db3aa752d9d4633c983c9d4bf5e48f9baff1/library/core/src/option.rs:1268:5
   3: core::result::Result<T,E>::unwrap
             at /home/icefox/.rustup/toolchains/beta-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/result.rs:973:23
   4: winit::main
             at ./examples/winit.rs:10:19
   5: core::ops::function::FnOnce::call_once
             at /home/icefox/.rustup/toolchains/beta-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/ops/function.rs:227:5
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
```

Let me know if there's anything else I can do to help.  You can set the `WINIT_UNIX_BACKEND=x11` environment variable and it works fine, at least.

**Comment by micahrj** [comment]
Appreciate the report! Yes, Wayland support is on my to-do list and I simply haven't gotten around to it yet.
